---
version: '3'
services:

  jenkins:
    image: docker.sunet.se/jenkins
    networks:
      jenkins_net:
    expose:
      - 50000
      - 8080
    volumes:
      - ../jenkins/jenkins_home:/var/jenkins_home:rw
      - ../bootstrap-docker-builds:/src/bootstrap-docker-builds:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /lib/x86_64-linux-gnu:/external_libs/lib64/:ro
      - /usr/lib/x86_64-linux-gnu/:/external_libs/usr/lib64:ro
    environment:
      - "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/external_libs/lib64:/external_libs/usr/lib64"
      - "JAVA_OPTS=-Djava.io.tmpdir=/var/jenkins_home/tmp"

  pound:
    image: docker.sunet.se/pound:latest
    networks:
      jenkins_net:
        ipv4_address: 172.16.12.100
    ports:
      - 443:443
    volumes:
      - ../pound/server.pem:/etc/ssl/private/jenkins.jenkins.docker.pem
    environment:
      - "BACKEND_PORT=tcp://jenkins:8080"
      - "REWRITE_LOCATION=0"
    depends_on:
      - jenkins


networks:
  jenkins_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.12.0/24
