---
version: '3.7'
services:

  jenkins:
    environment:
      DEV_MODE: "true"
      pullStrategy: PULL_NEVER
      # In PROD we need to supply a SLACK_TOKEN, in dev its defaults to empty
      #SLACK_TOKEN: "${SLACK_TOKEN}"
      REPOS: "${REPOS-}"
      ORGS: "${ORGS-}"
    volumes:
      # Add config based on mode
      - ../jcasc_configs/jenkins-dev_mode.yaml:/var/jenkins_home/casc_configs/jenkins-dev_mode.yaml:ro
      # Add the local docker-socket for running agents on.
      - /var/run/docker.sock:/var/run/docker.sock:rw

  git-bootstrap-docker-builds:
    image: docker.sunet.se/sunet/docker-jenkins
    ports:
      - 9418:9418
    volumes:
      - ../bootstrap-docker-builds:/src/bootstrap-docker-builds:ro
    entrypoint: /usr/bin/git daemon --verbose --base-path=/src/ --export-all

secrets:
  GNUPG_KEYRING:
    file: ${GNUPG_KEYRING:-~/.gnupg/pubring.kbx}
