---
version: '3.7'
services:

  jenkins:
    # We will use custom image with more plugins
    build: .
    # TODO: Move this to secrets?
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN?GITHUB_TOKEN not set, set it in .env}
      GITHUB_ADMIN_USERNAMES: ${GITHUB_ADMIN_USERNAMES?GITHUB_ADMIN_USERNAMES not set, set it in .env}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID not set, set it in .env}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET not set, set it in .env}
      SLACK_TOKEN: ${SLACK_TOKEN?SLACK_TOKEN not set, set it in .env}
      DOCKER_URI: ${DOCKER_URI?DOCKER_URI not set, set it in .env}
      GITHUB_ORGANIZATIONS: "{GITHUB_ORGANIZATIONS-SUNET}"
      ADMIN_ADDRESS: "${ADMIN_ADDRESS-dev@sunet.se}"
      JENKINS_URL: "${JENKINS_URL-ci.sunet.se}"
      REPOS: "${REPOS-}"
      ORGS: "${ORGS-}"

    volumes:
# Enable named jenkins_home volume if you would like a persistent jenkins_home
# Othervise, jcasc and job-dsl will populate one.
      - jenkins_home:/var/jenkins_home:rw
      # Add the local docker-socket for running agents on.
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Add config based on mode
      - ../jcasc_configs/jenkins-prod_mode.yaml:/var/jenkins_home/casc_configs/jenkins-prod_mode.yaml:ro
      - ../jcasc_configs/SSH_TO_CONNECT_AGENT_secret.groovy:/var/jenkins_home/init.groovy.d/SSH_TO_CONNECT_AGENT_secret.groovy:ro
    secrets:
      - PUBLISH_OVER_SSH_KEY
      - DOCKER_SERVER_CA_CERTIFICATE
      - DOCKER_CLIENT_CERTIFICATE
      - DOCKER_CLIENT_KEY

  pound:
    volumes:
      - ${DEHYDRATED_BUNDLE:?DEHYDRATED_BUNDLE not set, set it in .env}:/etc/ssl/private/ci.sunet.se.pem
      - ${DEHYDRATED_BUNDLE:?DEHYDRATED_BUNDLE not set, set it in .env}:/etc/ssl/private/ed-integrations.com.pem
      - ${DEHYDRATED_BUNDLE:?DEHYDRATED_BUNDLE not set, set it in .env}:/etc/ssl/private/${JENKINS_URL-empty}.pem

  always-https:
    image: docker.sunet.se/always-https
    ports:
      - 80:80
    environment:
      - "ACME_URL=http://${JENKINS_URL-empty}"

  registry:
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - jenkins
    networks:
      jenkins_net:

volumes:
  jenkins_home:

secrets:
  PUBLISH_OVER_SSH_KEY:
    file: ${PUBLISH_OVER_SSH_KEY?PUBLISH_OVER_SSH_KEY not set, set it in .env and point it to the right file}
  DOCKER_SERVER_CA_CERTIFICATE:
    file: ${DOCKER_SERVER_CA_CERTIFICATE:?DOCKER_SERVER_CA_CERTIFICATE not set, set it in .env and point it to the right file}
  DOCKER_CLIENT_CERTIFICATE:
    file: ${DOCKER_CLIENT_CERTIFICATE:?DOCKER_CLIENT_CERTIFICATE not set, set it in .env and point it to the right file}
  DOCKER_CLIENT_KEY:
    file: ${DOCKER_CLIENT_KEY:?DOCKER_CLIENT_KEY not set, set it in .env and point it to the right file}
  GNUPG_KEYRING:
    file: ${GNUPG_KEYRING:?GNUPG_KEYRING not set, set it in .env and point it to the right file}
