---
version: '3'
services:

  jenkins:
    # TODO: Move this to secrets?
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID not set, set it in .env}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET not set, set it in .env}
      SLACK_TOKEN: ${SLACK_TOKEN:?SLACK_TOKEN not set, set it in .env}
    volumes:
# Enable named jenkins_home volume if you would like a persistent jenkins_home
# Othervise, jcasc and job-dsl will populate one.
#      - jenkins_home:/var/jenkins_home:rw
      # Add config based on mode
      - ../jcasc_configs/jenkins-prod_mode.yaml:/var/jenkins_home/casc_configs/jenkins-prod_mode.yaml:ro

  pound:
    volumes:
      # TODO: Handle this in some other way?
      - <%= @dehydrated_bundle %>:/etc/ssl/private/ci.sunet.se.pem

  always-https:
    image: docker.sunet.se/always-https
    ports:
      - 80:80
    environment:
      - "ACME_URL=http://acme-c.sunet.se"
